### ISSUE TITLE
Does the Micro mode support multiple aspect ratios?

### ISSUE THREAD

**Issue by zakinp** [victorchall/EveryDream-trainer#14]
The question is the same as title. Because I found that the tedd's dataset is all composed of square images.

**Comment by victorchall** [comment]
Yes, it's a universal feature, HOWEVER when you mix aspect ratios you need a lot more images as each "bucket" of each aspect ratio must fill the batch_size.

I.e. if you have 13 images at 16:9 and your batch size is 4, 13 does not fit into 4 evenly, thus one image will be dropped.

If you have many hundreds of images the dropped images are not going to be a big deal.   If you only have 20 images you're better off making them all the same aspect ratio.  If all images are the same aspect ratio it will not drop anything regardless of batch size. 

So, for people just doing fast micro stuff you may  just be better off doing your own cropping to make them all the same aspect ratio.  Also, try to keep them all larger if you can.  540x540, 700x700, etc so crop jitter can do its magic.

Ted was created before I added multiaspect and crop jitter features.
