### ISSUE TITLE
error when trying to train a model

### ISSUE THREAD

**Issue by AntouanK** [victorchall/EveryDream-trainer#18]
I used the micromodels guide and trained a model twice. Second attempt was very good.
I was trying now to run again the same command, to train it again with another 1.5 variation and I get those errors.
Even using the same command/base model I used before, gives the same error.
Any idea why?

![image](https://user-images.githubusercontent.com/4569111/206671544-c1f55a6f-a06c-457b-948e-77932de520af.png)

**Comment by noprompt** [comment]
I encountered the same issue.

**Comment by victorchall** [comment]
I think you may be using the wrong yaml. 

Can you paste the entire command you're using to start training?

**Comment by Mitchnoff** [comment]
For anyone getting this issue, I encountered this same exact problem. The command in the github README uses v1-funetune, which I tried. As @victorchall mentioned, that was caused by using the wrong `.yaml` file. use the `v1-finetune_everydream.yaml` file instead. Worked for me.

**Comment by victorchall** [comment]
yeah I'm pretty sure thats what it is,  I suppose I'll just remove that file, it's a leftover from DB/TI stuff... @antoaunK let me know if its something else but 95% sure that's all it is.
