### ISSUE TITLE
Allow pruning script to prune with float32 instead if float16

### ISSUE THREAD

**Issue by ProGamerGov** [victorchall/EveryDream-trainer#19]
Currently your pruning script reduce the model size to 2GB at the cost of converting it to half precision. You should add an option to keep it full precision.

**Comment by 0xJustin** [comment]
I would also like this!

**Comment by victorchall** [comment]
From my experiments, there's no difference in quality from 2GB to 4GB.  If I prune a normal SD model from SAI/Compvis/Runyway, they produce the same output.  Are you finding otherwise?

**Comment by victorchall** [comment]
Looks like you issued a PR for this so no reason not to allow it if you want.

**Comment by ProGamerGov** [comment]
@victorchall In my experience, the overall image generally remains the same when using half precision, however some key details will differ. With half precision, these differences generally result in worse outputs than with the full precision version.
