### ISSUE TITLE
Running out of Memory on a 3090

### ISSUE THREAD

**Issue by Beliriel** [victorchall/EveryDream-trainer#7]
I have a model and want to train an art style with 8000 pictures. Since 8k is a bit much, I decided to cut the training it into pieces of 2000. I don't care about overtraining too much as long as it recognizes the token or artstyle from the prompts after.

Any batchsize bigger than 1 gives me

`RuntimeError: CUDA out of memory. Tried to allocate 9.99 GiB (GPU 0; 24.00 GiB total capacity; 5.07 GiB already allocated; 10.71 GiB free; 10.70 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF`

Why would I need to change the memory pages?

**Comment by victorchall** [comment]
Number of training images will not affect VRAM use.

Make sure you close out everything you can. Chrome can eat gigabytes with lots of tabs open.  You can turn off hardware acceleration in Discord and VS Code it just close them.

**Comment by victorchall** [comment]
You can also run "nvidia-smi" prior to starting the trainer to see how much VRAM is really being used, it is a bit more accurate than task manager.

**Comment by Beliriel** [comment]
I did run nvidia-smi and it showed me 400MB GPU usage before I started. I closed everything down except one or two firefox tabs on github (which really aren't that much)
