### ISSUE TITLE
Running but no checkpoints saved

### ISSUE THREAD

**Issue by celticsha** [victorchall/EveryDream-trainer#8]
Sometimes this runs beautifully on my pc. Other times, it seems to run but doesn't save anything to the checkpoints directory.

**Comment by victorchall** [comment]
By default the yamls provided will save a checkpoint at the end of every epoch.  Are you getting to the end of at least one epoch?  Should be when the main steps bar fills...

It may take a while if your repeats and number of training images is large. You can get checkpoints more frequently by reducing repeats in the config YAML.  Details are in the readme.

**Comment by celticsha** [comment]
Thank you for getting back to me. Possibly not getting to the end of the
first epoch. I've taken a look at the config file and I could see it's
already set to save a file per epoch, but what do I need to tweak if it's
not getting that far? I tried increasing steps but ran out of memory.

**Comment by victorchall** [comment]
The new code push will now lower system memory use, it should help quite a bit because the CKPT saving takes a lot of system ram, using either RAM or virtual memory/pagefile.   Hopefully this will get rid of quite a few of the problems people have on runpods when training thousands of images.

**Comment by victorchall** [comment]
Open a new issue if you still have issues on the latest code.  Full dump of your log will be helpful.
